sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: DemonJoker0rHB98
  alioss:
    endpoint: oss-cn-beijing.aliyuncs.com
    access-key-id: LTAI5t797kfzeQsmjLjS4rbF
    access-key-secret: rkE9D23Lag1OUJi9raIIn4RH62Ho6Q
    bucket-name: sky-take-out--yui
  redis:
    host: localhost
    port: 6379
    password: 123456
    database: 10